import React, { useState } from 'react';
import { View, StyleSheet, ScrollView, Share, Platform, Image } from 'react-native';
import { Text, Button, Surface, List, IconButton, ActivityIndicator } from 'react-native-paper';
import { MaterialCommunityIcons } from '@expo/vector-icons';

export default function ResultScreen({ route, navigation }) {
  const { reading, image } = route.params;
  const [expandedSection, setExpandedSection] = useState('handAnalysis');

  const sections = [
    { 
      id: 'handAnalysis',
      title: 'Hand Analysis',
      icon: 'hand-front-right',
      content: reading.handAnalysis 
    },
    { 
      id: 'majorLines',
      title: 'Major Lines',
      icon: 'fingerprint',
      content: reading.majorLines 
    },
    { 
      id: 'lifePath',
      title: 'Life Path',
      icon: 'road-variant',
      content: reading.lifePath 
    },
    { 
      id: 'personalityTraits',
      title: 'Personality Traits',
      icon: 'account-heart',
      content: reading.personalityTraits 
    },
    { 
      id: 'futureInsights',
      title: 'Future Insights',
      icon: 'crystal-ball',
      content: reading.futureInsights 
    }
  ];

  const handleShare = async () => {
    try {
      const message = sections.map(section => 
        `${section.title}:\n${section.content}\n\n`
      ).join('');
      
      await Share.share({
        message: `My Palm Reading\n\n${message}\n\nGenerated by Palm Reader App`,
        title: 'My Palm Reading'
      });
    } catch (error) {
      console.error('Error sharing reading:', error);
    }
  };

  return (
    <View style={styles.container}>
      <ScrollView>
        <Surface style={styles.surface}>
          {image && (
            <View style={styles.imageContainer}>
              <Image
                source={{ uri: `data:image/jpeg;base64,${image}` }}
                style={styles.palmImage}
                resizeMode="cover"
              />
            </View>
          )}

          <View style={styles.header}>
            <Text style={styles.title}>Your Palm Reading</Text>
            <IconButton
              icon="share-variant"
              size={24}
              onPress={handleShare}
              style={styles.shareButton}
            />
          </View>

          {sections.map((section) => (
            <List.Accordion
              key={section.id}
              title={section.title}
              left={props => <MaterialCommunityIcons name={section.icon} size={24} color={props.color} />}
              expanded={expandedSection === section.id}
              onPress={() => setExpandedSection(expandedSection === section.id ? null : section.id)}
              style={styles.accordion}
            >
              <View style={styles.contentContainer}>
                <Text style={styles.text}>{section.content}</Text>
              </View>
            </List.Accordion>
          ))}

          <Button
            mode="contained"
            onPress={() => navigation.navigate('Home')}
            style={styles.button}
            icon="camera"
          >
            Get Another Reading
          </Button>
        </Surface>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  surface: {
    margin: 20,
    padding: 10,
    elevation: 4,
    borderRadius: 15,
    backgroundColor: 'white',
  },
  imageContainer: {
    width: '100%',
    height: 200,
    marginBottom: 15,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#f0f0f0',
  },
  palmImage: {
    width: '100%',
    height: '100%',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    flex: 1,
  },
  shareButton: {
    margin: 0,
  },
  accordion: {
    backgroundColor: '#fff',
    borderRadius: 8,
    marginVertical: 4,
  },
  contentContainer: {
    padding: 16,
    backgroundColor: '#f8f8f8',
  },
  text: {
    fontSize: 16,
    lineHeight: 24,
    color: '#333',
  },
  button: {
    marginTop: 20,
    marginHorizontal: 10,
    marginBottom: 10,
    padding: 8,
    borderRadius: 8,
  },
}); 